language: node_js
git:
  depth: 3
node_js:
  - "node"
install: npm install
script:
  - npm test
  - gulp
cache:
  directories:
    - node_modules
notifications:
  email: false
deploy:
  provider: surge
  project: ./
  domain: bootstrap4-gulp.surge.sh
  skip_cleanup: true
